services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"

  ims-db:
    image: postgres:alpine
    container_name: ims-db
    environment:
      POSTGRES_DB : "ims"
      POSTGRES_PASSWORD: "mysecretpassword"
    restart: always
    ports:
      - '5432:5432'
    networks:
      - ecommerce
    volumes:
      - ecommerce


  auth-db:
    image: postgres:alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: "_auth"
      POSTGRES_PASSWORD: "mysecretpassword"
    restart: always
    ports:
      - '5433:5432'
    networks:
      - ecommerce
    volumes:
      - ecommerce

  carts-db:
    image: postgres:alpine
    container_name: carts-db
    environment:
      POSTGRES_DB: "_carts"
      POSTGRES_PASSWORD: "mysecretpassword"
    restart: always
    ports:
      - '5434:5432'
    networks:
      - ecommerce
    volumes:
      - ecommerce


  orders-db:
    image: postgres:alpine
    container_name: orders-db
    environment:
      POSTGRES_DB : "_orders"
      POSTGRES_PASSWORD: "mysecretpassword"
    restart: always
    ports:
      - "5435:5432"
    networks:
      - ecommerce
    volumes:
      - ecommerce

  ims-app:
    image: olymahmudmugdho/inventory-management-system
    container_name: ims-app
    ports:
      - "8081:8081"
    depends_on:
      - ims-db
      - kafka
    networks:
      - ecommerce
    volumes:
      - ecommerce


  auth-app:
    image: olymahmudmugdho/ecommerce-auth-microservice
    container_name: auth-app
    environment:
      DATABASE_URL : "postgresql://postgres:mysecretpassword@auth-db:5433/_auth"
      ACCESS_TOKEN_SECRET : "5511e1f7b6"
      REFRESH_TOKEN_SECRET : "2343342c2"
    ports:
      - "8082:8082"
    depends_on:
      - auth-db
    networks:
      - ecommerce
    volumes:
      - ecommerce

  cart-app:
    image: olymahmudmugdho/ecommerce-cart-microservice
    container_name: cart-app
    environment:
      DATABASE_URL : "postgresql://postgres:mysecretpassword@carts-db:5434/_carts"
    ports:
      - "8083:8083"
    depends_on:
      - carts-db
    networks:
      - ecommerce
    volumes:
      - ecommerce


  orders-app:
    image: olymahmudmugdho/ecommerce-order-microservice
    container_name: order-app
    ports:
      - "8084:8084"
    networks:
      - ecommerce
    volumes:
      - ecommerce

networks:
  ecommerce:
    driver: bridge

volumes:
  ecommerce: