services:
  ims-db:
    image: postgres:alpine
    container_name: ims-db
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    restart: always
    ports:
      - "5432:5432"
    networks:
      - ecommerce

networks:
  ecommerce:
    driver: bridge